// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0_P_0VpvV2MxavDnTMr2UuZtrT7YXdlE',
    appId: '1:461150462038:web:1d38505ef06923a6cb5bf7',
    messagingSenderId: '461150462038',
    projectId: 'todo-app-32c07',
    authDomain: 'todo-app-32c07.firebaseapp.com',
    storageBucket: 'todo-app-32c07.firebasestorage.app',
    measurementId: 'G-CMHR01GN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxYdX1dmct8tO52aDhUhhIMMu8TDASsw',
    appId: '1:461150462038:android:faa04830ed70832acb5bf7',
    messagingSenderId: '461150462038',
    projectId: 'todo-app-32c07',
    storageBucket: 'todo-app-32c07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUzhhfIDffAHpq34Mk20tQEUQfSOg-Tw',
    appId: '1:461150462038:ios:e587399e839ecec9cb5bf7',
    messagingSenderId: '461150462038',
    projectId: 'todo-app-32c07',
    storageBucket: 'todo-app-32c07.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUzhhfIDffAHpq34Mk20tQEUQfSOg-Tw',
    appId: '1:461150462038:ios:e587399e839ecec9cb5bf7',
    messagingSenderId: '461150462038',
    projectId: 'todo-app-32c07',
    storageBucket: 'todo-app-32c07.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0_P_0VpvV2MxavDnTMr2UuZtrT7YXdlE',
    appId: '1:461150462038:web:dd529199fa0cb56ecb5bf7',
    messagingSenderId: '461150462038',
    projectId: 'todo-app-32c07',
    authDomain: 'todo-app-32c07.firebaseapp.com',
    storageBucket: 'todo-app-32c07.firebasestorage.app',
    measurementId: 'G-BMM1BYCFJ7',
  );
}
